language: c

before_install:
  - sudo apt-get update
  - sudo apt-get install -q postgresql-server-dev-9.3 libcunit1-dev valgrind
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - sh .install-lazperf.sh

addons:
  postgresql: "9.3" # for "installcheck"

before_script:
  - npm install -g eclint
  - eclint check * */* */cunit/*
  - ./autogen.sh

script:
  - ./configure CFLAGS="-Wall -O2 -g -coverage" LDFLAGS="-lgcov" --with-lazperf=/usr/local/
  - make
  - make check
  - valgrind --leak-check=full --error-exitcode=1 lib/cunit/cu_tester
  - sudo make install
  - make installcheck || { cat pgsql/regression.diffs && false; }
  - cd tools/benchmark_compression && sh compression_benchmark.sh ; cd -
  - cd lib && gcov *.c ; cd -
  - cd lib/cunit && gcov *.c ; cd -
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

